# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2dcb9d8d634c14107a8ef202f6e6ba1fe2ac57a117bc4398be1851a6fb5fb8e0c3b22e4e9c67735ca85cd7490b273fd4283459a5575aff66998dd98d0e33d0

test:
  secret_key_base: e54f45cd148f991b08fb3e3f9e55fdd733f8b5142805a4ca5b5cb43a6185b6587fff2cbb7fb8e0d2a38755b4b6e0bf360d86219a0c85c80a8a253e557ce1fe57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
